- name: test gcp_compute_windows_pwd
  hosts: localhost
  connection: local
  vars_files:
  - files/gcp_vars

  tasks:
  - name: decrypt serviceaccount file
    copy:
      src: files/gcp-serviceaccount.json
      dest: files/gcp-cred.json
    
#  - name: show content file
#    debug: var=item
#    with_file:
#    - "/tmp/gcp-cred.json"
  
  - name: run the new module
    gcp_compute_win_password:
      instance: "{{ vm_name }}"
      zone: "{{ gcp_zone }}"
      project: "{{ gcp_project }}"
      email: "{{ gcp_email }}"
      credential_file: "/tmp/gcp-cred.json"
      username: "ansible"
    register: testout

  - name: dump test output
    debug:
      msg: "{{ testout }}"
