---
- name: Define and Load in the custom facts
  hosts: all
  gather_facts: yes
  
  vars_files:
  - winrm_vars
  
  vars:
    factpath: "C:\\Ansible\\CustomFacts"

  tasks:
    - name: create custom fact directory
      win_file:
        path: "{{ factpath }}"
        state: directory

    - name: set up custom facts
      template:
        src: facts.ps1
        dest: "{{ factpath }}"

    - name: reload facts
      setup:
        fact_path: "{{ factpath }}"
