---
- name: Define and Load in the custom facts
  hosts: all
  gather_facts: no
  
  vars_files:
  - files/winrm_vars
  
  tasks:
    - name: set a custom fact for the role
      set_fact:
        role: "{{ role }}"

    #- name: set up custom facts
    #  win_template:
    #    src: facts.ps1.j2
    #    dest: "{{ factpath }}\\facts.ps1"

    - name: reload facts
      setup:
