---
- name: create loadbalancer setup
  hosts: webservers
  vars_files:
    files/winrm_vars
    
  tasks:
  - name: create empty list for collection of backend servers
    set_fact:
      server_list: []

  - name: populate loadbalancer list of dictionaries
    set_fact:
        server_list: "{{ server_list + {'name': inventory_hostname, 'address': '{{ ansible_ssh_host }}' + ':80'} }}"
    #loop: "{{ groups['webservers'] }}"
    
  - name: debug
    debug:
      var: server_list

  - name: store the resulting pool for the next play
    set_stats:
      data:
        backend_server_list: "{{ server_list }}"
    #run_once: true
