---
# This playbook uses the win_get_url module to download a simple HTML file for IIS
- name: Deploy web site 
  hosts: webservers

  vars_files:
    files/winrm_vars

  gather_facts: false
  tasks:
    - name: Download web site to 'C:\inetpub\wwwroot\ansible.html'
      win_get_url:
        url: 'https://raw.githubusercontent.com/wzzrd/automates/master/templates/index.html'
        dest: 'C:\inetpub\wwwroot\index.html'
